name: AntiAutoFishing
version: '${version}'
api-version: '${apiVersion}'
main: com.codingguru.autofish.AntiAutoFish
authors: [CodingGuru]
permissions:
  autofish.bypass:
    description: Exempts a player from all auto-fishing checks.
    default: op
